services:
  db:
    image: mariadb:10.6
    env_file:
      - .env
    restart: always
    ports:
      - ${DOCKER_DB_PORT}:3306
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - ${DOCKER_DB_VOLUME}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
  app:
    image: nextcloud
    env_file:
      - .env
    restart: always
    ports:
      - ${DOCKER_APP_PORT}:80
    links:
      - db
    volumes:
      - ${DOCKER_STORAGE_VOLUME}:/var/www/html
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=${MYSQL_HOST}
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT}
      - PHP_UPLOAD_LIMIT=${PHP_UPLOAD_LIMIT}
